stages:
 - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

android:
  stage: build
  image: kazade/android-sdk
  script:
   - mkdir ${CI_PROJECT_DIR}/build

   # Download SDL and OpenAL-soft
   - cd ${CI_PROJECT_DIR}/platforms/android
   - python prepare.py

   # Build SDL
   - mkdir -p .android/sdl/build/jni
   - cd .android/sdl/build/jni
   - ln -s ../../Android.mk
   - ln -s ../../src
   - ln -s ../../include
   - cd ..
   - export APP_PLATFORM=android-18
   - NDK_PROJECT_PATH=. ndk-build
   # Return to our build directory
   - cd ${CI_PROJECT_DIR}/build
   - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
   - make

windows-mingw:
  stage: build
  image: fedora:28
  before_script:
   - dnf install -y mingw64-gcc-c++ mingw64-SDL2 mingw64-openal-soft mingw64-zlib cmake make gcc-c++ python
  script:
   - mkdir build
   - cd build
   - mingw64-cmake ..
   - make

