stages:
 - build

android:
  stage: build
  image: kazade/android-sdk
  script:
   - mkdir ${CI_PROJECT_DIR}/build

   # Download SDL and OpenAL-soft
   - cd ${CI_PROJECT_DIR}/platforms/android
   - python prepare.py
   - cat sdl_cmake_fix.txt >> .android/sdl/CMakeLists.txt
   - mkdir -p .android/sdl/build
   - cd .android/sdl/build
   # Build SDL
   - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
   - make
   # Return to our build directory
   - cd ${CI_PROJECT_DIR}/build
   - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
   - make

windows-mingw:
  stage: build
  image: fedora:28
  before_script:
   - dnf install -y mingw64-gcc-c++ mingw64-SDL2 mingw64-openal-soft mingw64-zlib cmake make gcc-c++ python
  script:
   - mkdir build
   - cd build
   - mingw64-cmake ..
   - make

