stages:
 - build
 - test
 - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

android:
  stage: build
  image: kazade/android-sdk
  allow_failure: true
  before_script:
   - apt-get install -y file
   - echo ${PATH}
  script:
   - mkdir ${CI_PROJECT_DIR}/build

   # Download SDL and OpenAL-soft
   - python ./platforms/android/prepare.py

   # Build SDL
   - mkdir -p .android/sdl/build/jni
   - cd .android/sdl/build/jni
   - ln -s ../../Android.mk
   - ln -s ../../src
   - ln -s ../../include
   - cd ..
   - export APP_PLATFORM=android-18
   - NDK_PROJECT_PATH=. ndk-build

   - cd ${CI_PROJECT_DIR}

   # Now OpenAL
   - mkdir -p .android/openal/build/jni
   - cd .android/openal/build/jni
   - ln -s ../../Android.mk
   - ln -s ../../OpenAL
   - cd ..
   - export APP_PLATFORM=android-18
   - NDK_PROJECT_PATH=. ndk-build

   # Finally Simulant
   - cd ${CI_PROJECT_DIR}/build
   - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
   - make

build:windows-x64-mingw:
  stage: build
  image: fedora:28
  before_script:
   - dnf install -y mingw64-gcc-c++ mingw64-SDL2 mingw64-openal-soft mingw64-zlib cmake make gcc-c++ python
  variables:
    MINGW_BIN_DIR: /usr/x86_64-w64-mingw32/sys-root/mingw/bin/
    TARGET: windows-x64-mingw
  script:
   - mkdir -p ${TARGET}/debug
   - cd ${TARGET}/debug
   - mingw64-cmake -DCMAKE_BUILD_TYPE=Debug -DSIMULANT_BUILD_SAMPLES=OFF ../..
   - make -j3
   - cp $MINGW_BIN_DIR/zlib1.dll simulant/
   - cp $MINGW_BIN_DIR/SDL2.dll simulant/
   - cp $MINGW_BIN_DIR/libgcc_s_seh-1.dll simulant/
   - cp $MINGW_BIN_DIR/libstdc++-6.dll simulant/
   - cp $MINGW_BIN_DIR/libwinpthread-1.dll simulant/
   - cp simulant/*.dll tests/
   - cd -
   - mkdir -p ${TARGET}/release
   - cd ${TARGET}/release
   - mingw64-cmake -DCMAKE_BUILD_TYPE=Release -DSIMULANT_BUILD_SAMPLES=OFF ../..
   - make -j3
   - cp $MINGW_BIN_DIR/zlib1.dll simulant/
   - cp $MINGW_BIN_DIR/SDL2.dll simulant/
   - cp $MINGW_BIN_DIR/libgcc_s_seh-1.dll simulant/
   - cp $MINGW_BIN_DIR/libstdc++-6.dll simulant/
   - cp $MINGW_BIN_DIR/libwinpthread-1.dll simulant/
  artifacts:
    paths:
      - ${TARGET}/debug/simulant/
      - ${TARGET}/debug/sample_data/
      - ${TARGET}/debug/tests/simulant_tests.exe
      - ${TARGET}/debug/tests/*.dll
      - ${TARGET}/release/simulant/*.dll

test:windows-x64-mingw:
  stage: test
  image: fedora:28
  allow_failure: true
  variables:
    TARGET: windows-x64-mingw
  dependencies:
   - build:windows-x64-mingw
  before_script:
   - dnf install -y wine winetricks wine-pulseaudio pulseaudio pulseaudio-utils xorg-x11-server-Xvfb xorg-x11-drv-dummy dpkg mesa-dri-drivers
   - start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 640x480x24 -ac +extension RANDR +extension GLX +render
   - sleep 3
   - export LIBGL_ALWAYS_SOFTWARE=1
   - export SIMULANT_SOUND_DRIVER=null
   - export DISPLAY=:99
  script:
   - cd ${TARGET}/debug
   - wine tests/simulant_tests.exe
  artifacts:
   paths:
    - ${TARGET}/debug/simulant/*.dll
    - ${TARGET}/release/simulant/*.dll

deploy:windows-x64-mingw:
  stage: deploy
  image: fedora:28
  dependencies:
   - test:windows-x64-mingw
  variables:
   TARGET: windows-x64-mingw
  before_script:
   - dnf -y install openssl-devel python-devel python-setuptools libffi-devel python-pip rsync
   - pip install gsutil
  script:
   - mkdir -p ./upload/${TARGET}/lib
   - mkdir -p ./upload/${TARGET}/lib/debug
   - mkdir -p ./upload/${TARGET}/include/simulant
   - cp ${TARGET}/release/simulant/*.dll ./upload/${TARGET}/lib/
   - cp ${TARGET}/debug/simulant/*.dll ./upload/${TARGET}/lib/debug/
   - rsync -avm --include='*.h' -f 'hide,! */' simulant ./upload/${TARGET}/include/simulant
   - cd upload
   - zip -r ${TARGET}.zip ${TARGET}/
   - echo -e "${GCS_ACCESS_KEY}\n${GCS_SECRET}\nsimulant-engine\n" | gsutil config -a
   - gsutil cp ${TARGET}.zip gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/
   - gsutil acl ch -u AllUsers:R gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/${TARGET}.zip
  artifacts:
   paths:
    - upload/${TARGET}.zip

build:linux-x64-gcc:
  stage: build
  image: fedora:28
  variables:
   TARGET: linux-x64-gcc
  before_script:
   - dnf upgrade -y
   - dnf install -y cmake make gcc-c++ python SDL2-devel openal-soft-devel zlib-devel mesa-libGL-devel
  script:
   - mkdir -p ${TARGET}/debug
   - cd ${TARGET}/debug
   - cmake -DCMAKE_BUILD_TYPE=Debug -DSIMULANT_BUILD_SAMPLES=OFF ../..
   - make -j3
   - cd ../..
   - mkdir -p ${TARGET}/release
   - cd ${TARGET}/release
   - cmake -DCMAKE_BUILD_TYPE=Release -DSIMULANT_BUILD_SAMPLES=OFF ../..
   - make -j3
  artifacts:
    paths:
      - ${TARGET}/debug/simulant/
      - ${TARGET}/debug/sample_data/
      - ${TARGET}/debug/tests/simulant_tests
      - ${TARGET}/release/simulant/

test:linux-x64-gcc:
  stage: test
  image: fedora:28
  dependencies:
   - build:linux-x64-gcc
  variables:
   TARGET: linux-x64-gcc
  before_script:
   - dnf install -y SDL2 openal-soft mesa-libGL libstdc++ pulseaudio pulseaudio-utils xorg-x11-server-Xvfb xorg-x11-drv-dummy dpkg mesa-dri-drivers
   - start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 640x480x24 -ac +extension RANDR +extension GLX +render
   - sleep 3
   - export LIBGL_ALWAYS_SOFTWARE=1
   - export DISPLAY=:99
  script:
   - cd ${TARGET}/debug
   - export SIMULANT_SOUND_DRIVER=null
   - env SEGFAULT_SIGNALS="abrt segv" LD_PRELOAD=/usr/lib64/libSegFault.so ./tests/simulant_tests
  artifacts:
   paths:
    - ${TARGET}/debug/simulant/
    - ${TARGET}/release/simulant/

deploy:linux-x64-gcc:
  stage: deploy
  image: fedora:28
  dependencies:
   - test:linux-x64-gcc
  variables:
   TARGET: linux-x64-gcc
  before_script:
   - dnf -y install openssl-devel python-devel python-setuptools libffi-devel python-pip rsync
   - pip install gsutil
  script:
   - mkdir -p ./upload/${TARGET}/lib
   - mkdir -p ./upload/${TARGET}/lib/debug
   - mkdir -p ./upload/${TARGET}/include/simulant
   - cp ${TARGET}/release/simulant/libsimulant.so.* ./upload/${TARGET}/lib/
   - cp ${TARGET}/debug/simulant/libsimulant.so.* ./upload/${TARGET}/lib/debug/
   - rsync -avm --include='*.h' -f 'hide,! */' simulant ./upload/${TARGET}/include/simulant
   - cd upload
   - zip -r ${TARGET}.zip ${TARGET}/
   - echo -e "${GCS_ACCESS_KEY}\n${GCS_SECRET}\nsimulant-engine\n" | gsutil config -a
   - gsutil cp ${TARGET}.zip gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/
   - gsutil acl ch -u AllUsers:R gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/${TARGET}.zip
  artifacts:
   paths:
    - upload/${TARGET}.zip

build:dreamcast-sh4-gcc:
  stage: build
  image: kazade/dreamcast-sdk
  variables:
   TARGET: dreamcast-sh4-gcc
  script:
   - mkdir -p ${TARGET}/release
   - cd ${TARGET}/release
   - source /etc/bash.bashrc
   - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../toolchains/Dreamcast.cmake -DSIMULANT_BUILD_SAMPLES=OFF ../..
   - make -j3
  artifacts:
    paths:
     - ${TARGET}/release/tests/simulant_tests.elf
     - ${TARGET}/release/simulant/
     - ${TARGET}/release/sample_data/

test:dreamcast-sh4-gcc:
  stage: test
  image: fedora:28
  allow_failure: true
  variables:
   TARGET: dreamcast-sh4-gcc
  dependencies:
    - build:dreamcast-sh4-gcc
  before_script:
    - dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    - dnf install -y lxdream
  script:
    - cd ${TARGET}/release
    - lxdream -H tests/simulant_tests.elf | tee log.out
  artifacts:
   paths:
    - ${TARGET}/release/simulant/*.a

deploy:dreamcast-sh4-gcc:
  stage: deploy
  image: fedora:28
  dependencies:
   - test:dreamcast-sh4-gcc
  variables:
   TARGET: dreamcast-sh4-gcc
  before_script:
   - dnf -y install openssl-devel python-devel python-setuptools libffi-devel python-pip rsync
   - pip install gsutil
  script:
   - mkdir -p ./upload/${TARGET}/lib
   - mkdir -p ./upload/${TARGET}/include/simulant
   - cp ${TARGET}/release/simulant/*.a ./upload/${TARGET}/lib/
   - rsync -avm --include='*.h' -f 'hide,! */' simulant ./upload/${TARGET}/include/simulant
   - cd upload
   - zip -r ${TARGET}.zip ${TARGET}/
   - echo -e "${GCS_ACCESS_KEY}\n${GCS_SECRET}\nsimulant-engine\n" | gsutil config -a
   - gsutil cp ${TARGET}.zip gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/
   - gsutil acl ch -u AllUsers:R gs://staging.simulant-engine.appspot.com/${CI_COMMIT_REF_NAME}/${TARGET}.zip
  artifacts:
   paths:
    - upload/${TARGET}.zip
