stages:
 - build
 - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

android:
  stage: build
  image: kazade/android-sdk
  allow_failure: true
  script:
   - mkdir ${CI_PROJECT_DIR}/build

   # Download SDL and OpenAL-soft
   - cd ${CI_PROJECT_DIR}/platforms/android
   - python prepare.py

   # Build SDL
   - mkdir -p .android/sdl/build/jni
   - cd .android/sdl/build/jni
   - ln -s ../../Android.mk
   - ln -s ../../src
   - ln -s ../../include
   - cd ..
   - export APP_PLATFORM=android-18
   - NDK_PROJECT_PATH=. ndk-build
   # Return to our build directory
   - cd ${CI_PROJECT_DIR}/build
   - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
   - make

windows-x64-mingw:build:
  stage: build
  image: fedora:28
  before_script:
   - dnf install -y mingw64-gcc-c++ mingw64-SDL2 mingw64-openal-soft mingw64-zlib cmake make gcc-c++ python
  script:
   - mkdir build-debug
   - cd build-debug
   - mingw64-cmake -DCMAKE_BUILD_TYPE=Debug -DSIMULANT_BUILD_SAMPLES=OFF ..
   - make -j3
   - cd ..
   - mkdir build-release
   - cd build-release
   - mingw64-cmake -DCMAKE_BUILD_TYPE=Release -DSIMULANT_BUILD_SAMPLES=OFF ..
   - make -j3
  artifacts:
    paths:
      - build-debug/simulant/
      - build-debug/tests/simulant_tests.exe

windows-x64-mingw:test:
  stage: test
  image: fedora:28
  before_script:
   - dnf install -y wine winetricks
  script:
   - cd build-debug
   - cp simulant/libsimulant.dll tests
   - wine tests/simulant_tests.exe

linux-x64-gcc:build:
  stage: build
  image: fedora:28
  before_script:
   - dnf install -y cmake make gcc-c++ python SDL2-devel openal-soft-devel zlib-devel mesa-libGL-devel
  script:
   - mkdir build-debug
   - cd build-debug
   - cmake -DCMAKE_BUILD_TYPE=Debug -DSIMULANT_BUILD_SAMPLES=OFF ..
   - make -j3
   - cd ..
   - mkdir build-release
   - cd build-release
   - cmake -DCMAKE_BUILD_TYPE=Release -DSIMULANT_BUILD_SAMPLES=OFF ..
   - make -j3
  artifacts:
    paths:
      - build-debug/simulant/
      - build-debug/tests/simulant_tests

linux-x64-gcc:test:
  stage: test
  image: fedora:28
  dependencies:
   - linux-x64-gcc:build
  script:
   - cd build-debug
   - ./tests/simulant_tests

dreamcast-sh4-gcc:build:
  stage: build
  image: kazade/dreamcast-sdk
  script:
   - mkdir build-release
   - cd build-release
   - source /etc/bash.bashrc
   - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../toolchains/Dreamcast.cmake -DSIMULANT_BUILD_SAMPLES=OFF ..
   - make -j3
  artifacts:
    paths:
      - build-release/simulant/
      - build-release/tests/simulant_tests.elf

dreamcast-sh4-gcc:test:
  stage: test
  image: fedora:28
  dependencies:
    - dreamcast-sh4-gcc:build
  before_script:
    - dnf install -y lxdream
  script:
    - cd build-release
    - lxdream -b -H -e tests/simulant_tests.elf

