sudo: required
os:
 - linux
 - osx
dist: trusty
language: cpp
git:
   submodules: false

env:
  # avoid ALSA errors
  - AUDIODEV=null

compiler:
 - gcc
 - clang

addons:
 apt: 
  packages:
   - libsdl2-dev 
   - libopenal-dev 
   - libtinyxml-dev
   - libxi-dev
   - libxmu-dev
   - xserver-xorg-video-dummy
   - xpra
   - xorg-dev
   - opencl-headers
   - libgl1-mesa-dev
   - libxcursor-dev
   - libpulse-dev
   - libxinerama-dev
   - libxrandr-dev
   - libxv-dev
   - libasound2-dev
   - libudev-dev
   - mesa-utils
   - libgl1-mesa-glx
   - xvfb
   - mesa-common-dev 
   - libglapi-mesa 
   - libgbm1 
   - libgl1-mesa-dri 
   - libxatracker-dev 
   - xvfb
   
before_install:
 - sh .prep-dummy-soundcard.sh
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
 - git submodule update --init --recursive
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tinyxml sdl2; fi

install:
 - mkdir build && cd build
 - cmake -DSIMULANT_BUILD_SAMPLES=OFF ..
 - make

before_script:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
  - sleep 3
  - glxinfo

script:
 - SDL_VIDEODRIVER=x11 ./tests/simulant_tests

matrix:
 allow_failures:
  - os: osx
