sudo: required
os:
 - linux
 - osx
dist: trusty
language: cpp
services: docker
git:
   submodules: false

env:
 global:
  - AUDIODEV=null
 matrix:
  - DREAMCAST=false
  - DREAMCAST=true

compiler:
 - gcc
 - clang

addons:
 apt: 
  packages:
   - libsdl2-dev 
   - libopenal-dev 
   - libtinyxml-dev
   - libxi-dev
   - libxmu-dev
   - xserver-xorg-video-dummy
   - xpra
   - xorg-dev
   - opencl-headers
   - libgl1-mesa-dev
   - libxcursor-dev
   - libpulse-dev
   - libxinerama-dev
   - libxrandr-dev
   - libxv-dev
   - libasound2-dev
   - libudev-dev
   - mesa-utils
   - xvfb
   - mesa-common-dev 
   - libgbm1 
   - libxatracker-dev 
   - xvfb
   - pulseaudio
   
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --install-recommends linux-generic-lts-xenial xserver-xorg-core-lts-xenial xserver-xorg-lts-xenial xserver-xorg-video-all-lts-xenial xserver-xorg-input-all-lts-xenial libwayland-egl1-mesa-lts-xenial; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
 - git submodule update --init --recursive
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tinyxml sdl2 openal-soft; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo usermod -a -G audio travis; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash ./.prep-dummy-soundcard.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dbus-launch pulseaudio --start; fi
 - if [[ "$DREAMCAST" == "true" ]]; then docker pull kazade/simulant-dc-test; fi

install:
 - mkdir build && cd build
 - if [[ "$DREAMCAST" == "false" ]]; then cmake -DSIMULANT_BUILD_SAMPLES=OFF ..; fi
 - if [[ "$DREAMCAST" == "false" ]]; then make; fi
 - if [[ "$DREAMCAST" == "true" ]]; then sudo docker run kazade/simulant-dc-test /bin/sh -c "source /etc/bash.bashrc; git clone --recursive --branch=${TRAVIS_BRANCH} https://github.com/${TRAVIS_REPO_SLUG}.git /simulant; mkdir -p /simulant/dbuild; cd /simulant/dbuild; cmake -DCMAKE_TOOLCHAIN_FILE=/simulant/toolchains/Dreamcast.cmake .. && make"; fi

before_script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LIBGL_ALWAYS_SOFTWARE=1; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ALSOFT_DRIVERS=pulse; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension RANDR +extension GLX +render; fi
 - sleep 3
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then glxinfo; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ $DREAMCAST == "false" ]]; then SDL_VIDEODRIVER=x11 catchsegv ./tests/simulant_tests; fi;
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/simulant_tests; fi;

matrix:
 allow_failures:
  - env: DREAMCAST=true
 exclude:
  - os: osx
    env: DREAMCAST=true
  - os: osx
    compiler: gcc
  - compiler: clang
    env: DREAMCAST=true

