sudo: required
os:
 - linux
 - osx
dist: trusty
language: cpp
git:
   submodules: false

compiler:
 - gcc
 - clang

addons:
 apt: 
  packages:
   - libsdl2-dev 
   - libopenal-dev 
   - libtinyxml-dev

before_install:
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive

install:
 - mkdir build && cd build
 - cmake ..
 - make

script:
 - ./tests/simulant_tests
 
matrix:
 allow_failures:
  - os: osx
