sudo: required
os:
 - linux
 - osx
dist: trusty
language: cpp
git:
   submodules: false

compiler:
 - gcc
 - clang

addons:
 apt: 
  packages:
   - libsdl2-dev 
   - libopenal-dev 
   - libtinyxml-dev
   - mesa-utils 
   - libgl1-mesa-swx11 
   - libgl1-mesa-swx11-dev 
   - xvfb  

before_install:
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive

install:
 - mkdir build && cd build
 - cmake ..
 - make

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - SDL_VIDEODRIVER=x11 ./tests/simulant_tests
 
matrix:
 allow_failures:
  - os: osx
